---
title: "About Me"
format: html
---

# San Diego, California 

I was born and raised in San Diego and have lived all of my life within the most southern county in California. Growing up in San Diego has been one of the biggest blessings in my life and I feel so grateful to have lived close to family and friends. My parents were also born and raised in San Diego and met at San Diego State University in the late 90s and decided to raise my sister and I here next to grandparents, aunts, uncles, and cousins. 

One of my favorite parts of living here is being so close to the beach. As a kid, the beach is what you do in the 

[insert picture of family w/ caption]

[insert picture of beach in SD w/ caption]

# Why UCSB & Environmental Studies?

When I was choosing which schools I wanted to apply to as a junior in high school, I could never have imagined that I would actually have ended up here at UCSB. I have had the most wonderful time and experiences going to college in Santa Barbara 

When it came to choosing my major, I thought about all of the things I wanted to be when I grew up - a teacher, a painter, an architect, a nurse, a marine biologist, a park ranger, and a . Eventually I landed on majoring in "Environmental Studies" because I thought it would be a way for me to combine what I loved, the outdoors and the ocean, with what I envisioned for my career path. Ultimately, my decision to pursue a degree in Environmental Studies 

[insert picture of UCSB w/ caption]

[insert grad pic w/ caption]


# My Interests 

## Environmental Education

My dad has been a middle school science teacher my whole life and has rooted in me a passion for education and 

In my third and fourth year, I have taken several courses in environmental and science education.  

[insert pic of WYP w/ caption]

## Restoration 

I am also passionate about habitat restoration and the re-wilding natural places. I have taken courses like "Conservation Planning", "Restoration Skills", and "Biodiversity & Conservation Biology" which have taught me about what it means to conserve habitats for both the species that live there and the people who derive ecosystem services from natural spaces. 

I have also worked as a Student Restoration Worker at the Cheadle Center for Biodiversity & Ecological Restoration (CCBER) 

[insert pic of working at CCBER]

## Coastal & Marine Ecosystems 

I am an ocean lover at heart and 

[insert picture of ocean]
