---
title: "Projects"
format: html
---

Here are a few projects that I have done during undergrad here at UCSB

# Homework 1

## Statistics for Environmental Science (ENV S 193DS)

This assignment was my first homework that I did in R Studio and created a Word document as the rendered output. In this assignment I got practice setting up a new project in R, organizing my file structure, visualizing data from a provided data set, critiquing other statistical analyses, and thinking about how I was going to set up my own personal data project. It contains a mix of code and written responses. 

[🌸 Homework 1 (PDF)](projects_files/homework1.pdf){target="_blank"}

# Environmental Education Portfolio

## Advanced Environmental Edcuation & Practicum (ENV S 127B)

This portfolio includes the project proposal, lesson plans, lesson materials, teaching reflections, and student work that I created and compiled for my quarter-long project titled “Integrating Environmental & Climate Change Education with Next Generation Science Standards (NGSS) in Classroom Settings: How can we as future teachers can become better prepared to teach about climate change”

[🌸 Environmental Education Project (PDF)](projects_files/EE_portfolio.pdf){target="_blank"}

# The People’s Tour: A New Paradigm for Cultural Tourism - Ocean Beach, San Diego, CA

## Global Tourism & Environmental Justice (ENV S 130B)

This project was focused on changing the narrative of a place and re-framing a typical tourism view of a location into how it is viewed by the people who actually live there. I decided to do Ocean Beach, an eclectic beach neighborhood in San Diego, that typically gets a bad rap for being overly bohemian. Through this paper, I designed "A People's Tour" of OB to showcase its rich social and cultural history.

[🌸 A People's Tour of OB (PDF)](projects_files/130b_paper.pdf){target="_blank"}
